const { request } = require('../../utils/request')
const app = getApp()
function field(item, names, fallback = '') { for (const name of names) if (item && item[name] !== undefined && item[name] !== null) return item[name]; return fallback }
function fullUrl(path) { if (!path) return ''; return /^https?:\/\//.test(path) ? path : `${app.globalData.baseUrl}${path.startsWith('/') ? '' : '/'}${path}` }
function isPdf(name) { return /\.pdf$/i.test(name || '') }
const VIDEO_RE = /\.(mp4|avi|rmvb|mov|m4v|flv|mkv|webm|wmv|mpg|mpeg|3gp)$/i
const AUDIO_RE = /\.(mp3|wav|m4a|aac|ogg|flac|amr|wma)$/i
function mapFiles(list) { return (list || []).map(f => { const filePath = field(f, ['filePath', 'url', 'name'], ''); const fileName = field(f, ['fileName', 'originalFilename'], filePath.split('/').pop()); return { ...f, filePath, fileName, url: fullUrl(filePath), isImage: !isPdf(fileName) && /\.(png|jpe?g|gif|webp)$/i.test(filePath), isVideo: VIDEO_RE.test(fileName) || VIDEO_RE.test(filePath), isAudio: AUDIO_RE.test(fileName) || AUDIO_RE.test(filePath), showName: fileName || '附件' } }) }
function upload(path, name, size) { return new Promise((resolve, reject) => wx.uploadFile({ url: `${app.globalData.baseUrl}/common/upload`, filePath: path, name: 'file', header: { Authorization: `Bearer ${wx.getStorageSync('token')}` }, success: r => { try { const d = JSON.parse(r.data); d.code === 200 ? resolve({ fileName: d.fileName || name, filePath: d.fileName || d.filePath || d.url, fileSize: size || 0 }) : reject(new Error(d.msg || '上传失败')) } catch (e) { reject(new Error('上传响应解析失败')) } }, fail: e => reject(new Error(e.errMsg || '上传失败')) })) }
Page({
  data: { id: null, scheduleId: '', detail: {}, homeworkFiles: [], description: '', files: [], submitted: false, loading: false, submitting: false },
  onLoad(q) { this.setData({ id: q.id, scheduleId: q.scheduleId || '' }); this.loadDetail() },
  async loadDetail() { this.setData({ loading: true }); try { const res = await request({ url: `/miniapp/parent/homework/${this.data.id}${this.data.scheduleId ? `?scheduleId=${this.data.scheduleId}` : ''}` }); const d = res.data || {}; const detail = d.homework || d; const submission = d.submission || null; const myFiles = (d.submissionFiles || (submission && (submission.files || submission.params && submission.params.files)) || []).concat(); this.setData({ detail: { ...detail, submission }, homeworkFiles: mapFiles(d.files), description: field(submission, ['description', 'answerText'], ''), files: mapFiles(myFiles), submitted: !!submission }) } catch (e) { wx.showToast({ title: e.message || '加载失败', icon: 'none' }) } finally { this.setData({ loading: false }) } },
  openFile(e) { const { url, name } = e.currentTarget.dataset; if (!url) return; if (/\.pdf$/i.test(url)) { wx.showLoading({ title: '打开中' }); wx.downloadFile({ url, success: r => { wx.hideLoading(); if (r.statusCode === 200) wx.openDocument({ filePath: r.tempFilePath, showMenu: true, fail: () => wx.showToast({ title: '无法打开该文件', icon: 'none' }) }); else wx.showToast({ title: '文件下载失败', icon: 'none' }) }, fail: () => { wx.hideLoading(); wx.showToast({ title: '文件下载失败', icon: 'none' }) } }) } else { wx.previewImage({ current: url, urls: [url] }) } },
  inputDescription(e) { this.setData({ description: e.detail.value }) },
  playAudio(e) { const url = e.currentTarget.dataset.url; if (!url) return; if (!this.audioCtx) { this.audioCtx = wx.createInnerAudioContext(); this.audioCtx.onPlay(() => wx.showToast({ title: '播放中', icon: 'none' })); this.audioCtx.onError(() => wx.showToast({ title: '音频播放失败', icon: 'none' })) } if (this.audioCtx.src !== url) { this.audioCtx.stop() } this.audioCtx.src = url; this.audioCtx.play() },
  onUnload() { if (this.audioCtx) { this.audioCtx.destroy(); this.audioCtx = null } },
  chooseImage() { wx.chooseImage({ count: 9, sizeType: ['compressed'], sourceType: ['album', 'camera'], success: r => r.tempFiles.forEach(f => this.addFile(f.path, f.name || f.path.split('/').pop(), f.size)) }) },
  chooseVideo() { wx.chooseMedia({ count: 3, mediaType: ['video'], sourceType: ['album', 'camera'], maxDuration: 60, success: r => r.tempFiles.forEach(f => this.addFile(f.tempFilePath, (f.tempFilePath || '').split('/').pop(), f.size)) }) },
  chooseAudio() { wx.chooseMessageFile({ count: 3, type: 'file', extension: ['mp3', 'wav', 'm4a', 'aac', 'ogg', 'flac', 'amr', 'wma'], success: r => r.tempFiles.forEach(f => this.addFile(f.path, f.name, f.size)) }) },
  choosePdf() { wx.chooseMessageFile({ count: 1, type: 'file', extension: ['pdf'], success: r => { const f = r.tempFiles[0]; if (f && f.name.toLowerCase().endsWith('.pdf')) this.addFile(f.path, f.name, f.size); else wx.showToast({ title: '仅支持 PDF 文件', icon: 'none' }) } }) },
  async addFile(path, name, size) { try { wx.showLoading({ title: '上传中' }); const file = await upload(path, name, size); wx.hideLoading(); this.setData({ files: this.data.files.concat([mapFiles([file])[0]]) }) } catch (e) { wx.hideLoading(); wx.showToast({ title: e.message || '附件上传失败', icon: 'none' }) } },
  removeFile(e) { if (this.data.submitted) return; const files = this.data.files.slice(); files.splice(Number(e.currentTarget.dataset.index), 1); this.setData({ files }) },
  async submit() { if (this.data.submitted || this.data.submitting) return; this.setData({ submitting: true }); try { await request({ url: '/miniapp/parent/homework/submit', method: 'POST', data: { homeworkId: this.data.id, enrollmentId: field(this.data.detail, ['enrollmentId']), answers: [], files: this.data.files.map(f => ({ fileName: f.fileName, filePath: f.filePath, fileSize: f.fileSize })), description: this.data.description } }); this.setData({ submitted: true }); wx.showToast({ title: '提交成功', icon: 'success' }) } catch (e) { wx.showToast({ title: e.message || '提交失败', icon: 'none' }) } finally { this.setData({ submitting: false }) } }
})
