-- 作业一期表结构
DROP TABLE IF EXISTS `edu_homework_file`;
DROP TABLE IF EXISTS `edu_homework_answer`;
DROP TABLE IF EXISTS `edu_homework_submission`;
DROP TABLE IF EXISTS `edu_homework_question`;
DROP TABLE IF EXISTS `edu_homework`;
CREATE TABLE `edu_homework` (`homework_id` bigint NOT NULL AUTO_INCREMENT,`schedule_id` bigint NOT NULL,`teacher_id` bigint NOT NULL,`title` varchar(200) NOT NULL,`description` varchar(2000) DEFAULT '',`deadline` datetime DEFAULT NULL,`publish_time` datetime DEFAULT NULL COMMENT '发布时间',`status` char(1) DEFAULT '0' COMMENT '0草稿1已发布2已关闭',`del_flag` char(1) DEFAULT '0',`total_score` int DEFAULT 0,`archive_flag` char(1) DEFAULT '0',`create_by` varchar(64) DEFAULT '',`create_time` datetime DEFAULT NULL,`update_by` varchar(64) DEFAULT '',`update_time` datetime DEFAULT NULL,PRIMARY KEY (`homework_id`),KEY `idx_homework_schedule` (`schedule_id`),KEY `idx_homework_teacher` (`teacher_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='作业';
CREATE TABLE `edu_homework_question` (`question_id` bigint NOT NULL AUTO_INCREMENT,`homework_id` bigint NOT NULL,`question_type` varchar(20) NOT NULL COMMENT 'single/judge/fill/image',`question_text` varchar(2000) NOT NULL,`options_json` text,`correct_answer` varchar(500) DEFAULT '',`score` int DEFAULT 0,`sort_no` int DEFAULT 0,`create_by` varchar(64) DEFAULT '',`create_time` datetime DEFAULT NULL,PRIMARY KEY (`question_id`),KEY `idx_question_homework` (`homework_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='作业题目';
CREATE TABLE `edu_homework_submission` (`submission_id` bigint NOT NULL AUTO_INCREMENT,`homework_id` bigint NOT NULL,`enrollment_id` bigint NOT NULL,`parent_id` bigint NOT NULL,`submit_time` datetime DEFAULT NULL,`auto_score` int DEFAULT 0,`manual_score` int DEFAULT 0,`final_score` int DEFAULT 0,`status` char(1) DEFAULT '1' COMMENT '1待批阅2已批阅',`teacher_comment` varchar(1000) DEFAULT '',`reviewer_id` bigint DEFAULT NULL,`review_time` datetime DEFAULT NULL,`description` varchar(2000) DEFAULT '',`create_by` varchar(64) DEFAULT '',`create_time` datetime DEFAULT NULL,`update_by` varchar(64) DEFAULT '',`update_time` datetime DEFAULT NULL,PRIMARY KEY (`submission_id`),UNIQUE KEY `uk_homework_enrollment` (`homework_id`,`enrollment_id`),KEY `idx_submission_parent` (`parent_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='作业提交';
CREATE TABLE `edu_homework_answer` (`answer_id` bigint NOT NULL AUTO_INCREMENT,`submission_id` bigint NOT NULL,`question_id` bigint NOT NULL,`answer_text` text,`correct_flag` char(1) DEFAULT '2',`score` int DEFAULT 0,`teacher_comment` varchar(500) DEFAULT '',`create_by` varchar(64) DEFAULT '',`create_time` datetime DEFAULT NULL,PRIMARY KEY (`answer_id`),KEY `idx_answer_submission` (`submission_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='作业答案';
CREATE TABLE `edu_homework_target` (`homework_id` bigint NOT NULL,`schedule_id` bigint NOT NULL,PRIMARY KEY (`homework_id`,`schedule_id`),KEY `idx_target_schedule` (`schedule_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='作业发布班级';
CREATE TABLE `edu_homework_file` (`file_id` bigint NOT NULL AUTO_INCREMENT,`homework_id` bigint NOT NULL,`submission_id` bigint DEFAULT NULL,`answer_id` bigint DEFAULT NULL,`file_type` varchar(20) NOT NULL COMMENT 'homework/submission/answer',`file_name` varchar(255) DEFAULT '',`file_path` varchar(500) NOT NULL COMMENT '现有文件存储路径',`file_size` bigint DEFAULT 0,`create_by` varchar(64) DEFAULT '',`create_time` datetime DEFAULT NULL,PRIMARY KEY (`file_id`),KEY `idx_file_homework` (`homework_id`),KEY `idx_file_submission` (`submission_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='作业图片文件';
